baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ash"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      blockLevel = true
      smartypants = true


[menu]
  [[menu.main]]
    name = "Features"
    url = "/#features"
    weight = 1
  [[menu.main]]
    name = "Solution"
    url = "/#solution"
    weight = 2
  [[menu.main]]
    name = "Reviews"
    url = "/#reviews"
    weight = 3
  [[menu.main]]
    name = "NextJS Version"
    url = "https://github.com/luasenvy/nextjs-astro-theme"
    weight = 4
  # Left Column Links
  [[menu.footer_left]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.footer_left]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.footer_left]]
    name = "Guide"
    url = "/guide"
    weight = 3
  [[menu.footer_left]]
    name = "Blocks"
    url = "/blocks"
    weight = 4
  [[menu.footer_left]]
    name = "Contact"
    url = "/contact"
    weight = 5
  [[menu.footer_left]]
    name = "Terms of Use"
    url = "/terms"
    weight = 6

  # Social Links
  [[menu.footer_social]]
    name = "Github"
    url = "https://github.com"
    pre = '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-5" viewBox="0 0 16 16"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/></svg>'
    weight = 1
  [[menu.footer_social]]
    name = "Twitter"
    url = "https://twitter.com"
    pre = '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-5" viewBox="0 0 16 16"><path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/></svg>'
    weight = 2
  [[menu.footer_social]]
    name = "YouTube"
    url = "https://youtube.com"
    pre = '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-5" viewBox="0 0 16 16"><path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/></svg>'
    weight = 3
[params]
  footer_description = "We change the way UI components libraries are used"
  footer_copyright = "Tailus Blocks"
  footer_terms_url = "/terms"
  footer_privacy_url = "/privacy"
  footer_contact_url = "/contact"
  clients = [
    { name = "Microsoft", logo = "/images/clients/microsoft.svg" },
    { name = "Airbnb", logo = "/images/clients/airbnb.svg" },
    { name = "Google", logo = "/images/clients/google.svg" },
    { name = "GE", logo = "/images/clients/ge.svg" },
    { name = "Netflix", logo = "/images/clients/netflix.svg" },
    { name = "Google Cloud", logo = "/images/clients/google-cloud.svg" }
  ]
  features = [
    { title = "First feature", description = "Neque Dolor, fugiat non cum doloribus aperiam voluptates nostrum.", icon = "https://cdn-icons-png.flaticon.com/512/4341/4341139.png", link = "#" },
    { title = "Second feature", description = "Neque Dolor, fugiat non cum doloribus aperiam voluptates nostrum.", icon = "https://cdn-icons-png.flaticon.com/512/4341/4341134.png", link = "#" },
    { title = "Third feature", description = "Neque Dolor, fugiat non cum doloribus aperiam voluptates nostrum.", icon = "https://cdn-icons-png.flaticon.com/512/4341/4341160.png", link = "#" },
    { title = "More features", description = "Neque Dolor, fugiat non cum doloribus aperiam voluptates nostrum.", icon = "https://cdn-icons-png.flaticon.com/512/4341/4341025.png", link = "#" }
  ]
   reviews = [
    { name = "Daniella Doe", role = "Mobile dev", avatar = "/images/avatars/avatar.webp", text = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum aliquid quo eum quae quos illo earum ipsa doloribus nostrum minus libero aspernatur laborum cum, a suscipit, ratione ea totam ullam! Lorem ipsum dolor sit amet consectetur, adipisicing elit..." },
    { name = "Jane Doe", role = "Marketing", avatar = "/images/avatars/avatar-1.webp", text = "Lorem ipsum dolor laboriosam deleniti aperiam ab veniam sint non cumque quis tempore cupiditate. Sint libero voluptas veniam at reprehenderit..." },
    { name = "Yanick Doe", role = "Developer", avatar = "/images/avatars/avatar-2.webp", text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto laboriosam deleniti aperiam ab veniam sint non cumque quis tempore cupiditate. Sint libero voluptas veniam at reprehenderit, veritatis harum et rerum." },
    { name = "Jane Doe", role = "Mobile dev", avatar = "/images/avatars/avatar-3.webp", text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto laboriosam deleniti aperiam ab veniam sint non cumque quis tempore cupiditate. Sint libero voluptas veniam at reprehenderit, veritatis harum et rerum." },
    { name = "Andy Doe", role = "Manager", avatar = "/images/avatars/avatar-4.webp", text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto laboriosam deleniti aperiam ab veniam sint non cumque quis tempore cupiditate. Sint libero voluptas veniam at reprehenderit, veritatis harum et rerum." },
    { name = "Yanndy Doe", role = "Mobile dev", avatar = "/images/avatars/avatar-2.webp", text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto laboriosam deleniti aperiam ab veniam sint non cumque quis tempore cupiditate. Sint libero voluptas veniam at reprehenderit, veritatis harum et rerum." }
  ]
  blogPosts = [
    { title = "De fuga fugiat lorem ispum laboriosam expedita.", description = "Voluptates harum aliquam totam, doloribus eum impedit atque! Temporibus...", image = "https://images.unsplash.com/photo-1661749711934-492cd19a25c3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80", link = "#" },
    { title = "De fuga fugiat lorem ispum laboriosam expedita.", description = "Voluptates harum aliquam totam, doloribus eum impedit atque! Temporibus...", image = "https://images.unsplash.com/photo-1491895200222-0fc4a4c35e18?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80", link = "#" },
    { title = "De fuga fugiat lorem ispum laboriosam expedita.", description = "Voluptates harum aliquam totam, doloribus eum impedit atque! Temporibus...", image = "https://images.unsplash.com/photo-1620121692029-d088224ddc74?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80", link = "#" }
  ]
   avatars = [
    { image = "/images/avatars/avatar.webp", alt = "member photo", width = "400", height = "400", class = "h-8 w-8 rounded-full object-cover" },
    { image = "/images/avatars/avatar-2.webp", alt = "member photo", width = "200", height = "200", class = "h-12 w-12 rounded-full object-cover" },
    { image = "/images/avatars/avatar-3.webp", alt = "member photo", width = "200", height = "200", class = "z-10 h-16 w-16 rounded-full object-cover" },
    { image = "/images/avatars/avatar-4.webp", alt = "member photo", width = "200", height = "200", class = "relative h-12 w-12 rounded-full object-cover" },
    { image = "/images/avatars/avatar-1.webp", alt = "member photo", width = "200", height = "200", class = "h-8 w-8 rounded-full object-cover" }
  ]
