baseURL = 'https://matterize.io/'
languageCode = 'en-us'
title = 'Matterize Labs - Your Matter Smart Home Development Partner'
theme = 'main'

# Enable Hugo Pipes processing
[build]
  writeStats = true
