name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

# Prevents concurrent deployments
concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Needed if you use SCSS/SASS

      - name: Cache Hugo dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build Hugo site
        run: hugo --minify

      - name: Check public directory
        run: |
          if [ -z "$(ls -A ./public 2>/dev/null)" ]; then
            echo "Error: Public directory is empty or doesn't exist!"
            mkdir -p ./public
            echo "<html><body><h1>Placeholder</h1></body></html>" > ./public/index.html
            echo "Created placeholder file to prevent empty artifact"
          else
            echo "Public directory contains:"
            ls -la ./public
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
